name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v12
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v6
    - run: sbt -v scalafmtSbtCheck "+ scalafmtCheckAll" "+ test"
    - run: rm -rf "$HOME/.ivy2/local"
